### PR TITLE
Fix: Typo

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] fixes a typo

Replaces https://github.com/spryker/spryker-core/pull/9.

### CODE REVIEW

**Comment by localheinz** [comment]
@dereuromark 

This process sounds like a lot of fun for everyone involved!

🤦‍♂️

**Comment by localheinz** [comment]
@dereuromark 

Build failure appears to be unrelated, looks like `master` has been broken for a while.

**Comment by dereuromark** [comment]
We put this into our backlog for a planned major
With the BC breaking impact this has, we cannot just do it now as a minor it seems.

**Comment by localheinz** [comment]
@dereuromark 

🤷‍♂️

**Comment by artem-png** [comment]
Dear @localheinz,

We want to express our appreciation for your recent contribution to our project.

Your pull request has been diligently reviewed, processed following our internal processes, and successfully merged into our codebase. It is now part of the release, which you can find under the [1.23.0](https://github.com/spryker/data-import/releases/tag/1.23.0).

Thanks a lot for your contribution!

Best,
Spryker Team

**Pull request closed without merging**
